### ISSUE TITLE
Schematic for connection ?

### ISSUE THREAD

**Issue by autonomobil** [olkal/LCD_ST7032#2]
I have also this type of ERC1602FYG-4 display (https://www.buydisplay.com/default/i2c-cog-16x2-character-lcd-display-module-st7032-serial-black-on-yg). 

How do you connect it to an Arduino Nano with SDA on Pin A4 und SCL on PIN A5? I connected like shown here, but the LCD stays dark: http://www.buydisplay.com/download/interfacing/ERC1602-4_Interfacing.pdf

**Comment by olkal** [comment]
Hi
Yes, A4 SDA and A5 SCL. I used the same schematic exept that I tied the RESET pin from the display to VDD. I'm sure you have checked everything but it really should work if the wiring and components is correct and the contrast is within the range.
